### ISSUE TITLE
plant genomes making database error

### ISSUE THREAD

**Issue by cfz1998** [qiyunlab/HGTector#102]
Hi! Everyone.
When i made a database for plant.I got a error.
```python
Database building started at 2022-09-11 11:50:50.246855.
Downloading NCBI taxonomy database... done.
Reading NCBI taxonomy database... done.
  Total number of TaxIDs: 2442703.
Downloading RefSeq assembly summary... done.
Reading RefSeq assembly summary... done.
  Total number of genomes: 272577.
Genome categories: plant
Downloading genome list per RefSeq category...
  plant: 154
Done.
  Total number of genomes in categories: 154.
Filtering genomes...
Done.
Filtering genomes by taxonomy...
Done.
Traceback (most recent call last):
  File "/data/chaofan/miniconda/envs/hgtector/bin/hgtector", line 96, in <module>
    main()
  File "/data/chaofan/miniconda/envs/hgtector/bin/hgtector", line 35, in main
    module(args)
  File "/data/chaofan/miniconda/envs/hgtector/lib/python3.10/site-packages/hgtector/database.py", line 148, in __call__
    self.filter_to_sampled()
  File "/data/chaofan/miniconda/envs/hgtector/lib/python3.10/site-packages/hgtector/database.py", line 591, in filter_to_sampled
    raise ValueError('No genome is retained after sampling.')
ValueError: No genome is retained after sampling.
```

The running code:
```shell
hgtector database -o db_dir --cats plant --threads 32
```
Thank you for your reply!
      --zcf

**Comment by qiyunzhu** [comment]
Hello @cfz1998 Thanks for reporting this issue. This problem happened because your command didn't specify how many genomes will be sampled per taxonomic group (e.g., using `--sample 1`).

I have tweaked the code so that it defaults to containing all genomes, such that your current command will work. To update the program, you can do:

```bash
pip install --force-reinstall --no-cache-dir git+https://github.com/qiyunlab/HGTector.git
```

**Comment by cfz1998** [comment]
> 
Thank you!

**Comment by cfz1998** [comment]
> Hello @cfz1998 Thanks for reporting this issue. This problem happened because your command didn't specify how many genomes will be sampled per taxonomic group (e.g., using `--sample 1`).
> 
> I have tweaked the code so that it defaults to containing all genomes, such that your current command will work. To update the program, you can do:
> 
> ```shell
> pip install --force-reinstall --no-cache-dir git+https://github.com/qiyunlab/HGTector.git
> ```

Hi! qiyun
I find a new issue:
```shell
# The code:
hgtector database -o db_dir --cat plant,archaea,bacteria,fungi,protozoa --threads 32
```
Error message:
```python
Database building started at 2022-09-14 10:51:27.131615.
Downloading NCBI taxonomy database... done.
Reading NCBI taxonomy database... done.
  Total number of TaxIDs: 2442723.
Downloading RefSeq assembly summary... done.
Reading RefSeq assembly summary... done.
  Total number of genomes: 272849.
Genome categories: plant, archaea, bacteria, fungi, protozoa
Downloading genome list per RefSeq category...
  plant: 154
  archaea: 1322
  bacteria: 1322
  fungi: 1322
  protozoa: 1322
Done.
  Total number of genomes in categories: 1476.
Filtering genomes...
Done.
Filtering genomes by taxonomy...
Done.
Total number of sampled genomes: 1476.
Downloading non-redundant genomic data from NCBI...
Traceback (most recent call last):
  File "/data/chaofan/miniconda/envs/hgtector/bin/hgtector", line 96, in <module>
    main()
  File "/data/chaofan/miniconda/envs/hgtector/bin/hgtector", line 35, in main
    module(args)
  File "/data/chaofan/miniconda/envs/hgtector/lib/python3.10/site-packages/hgtector/database.py", line152, in __call__
    self.download_genomes()
  File "/data/chaofan/miniconda/envs/hgtector/lib/python3.10/site-packages/hgtector/database.py", line622, in download_genomes
    makedirs(ldir, exist_ok=True)
  File "/data/chaofan/miniconda/envs/hgtector/lib/python3.10/os.py", line 225, in makedirs
    mkdir(name, mode)
FileExistsError: [Errno 17] File exists: 'db_dir/download/faa'
```

**Comment by cfz1998** [comment]
When i download data for a query list. [count 1336]
It's only download the default nr protein(archaea bacteria fungi protozoa). [count 1322]
[genbank.txt](https://github.com/qiyunlab/HGTector/files/9574083/genbank.txt)

**Comment by qiyunzhu** [comment]
Hi @cfz1998 I don't quite understand your last question. Can you elaborate?

**Comment by cfz1998** [comment]
> 你好！ 就是我通过-g 参数来构建数据库，提供的NCBI assembly accessions列表里包括了1336个物种。其中有1322个物种是属于(archaea bacteria fungi protozoa)，这1322个物种也是使用--default参数自动下载的，其他14个物种是一些植物。 但是hgtector只构建了1322个物种的数据库，并没有包括我额外添加的这14个植物物种。

**Comment by qiyunzhu** [comment]
@cfz1998 Most likely it was because the 14 additional species do not have certain metadata fields available, especially taxonomic classification, thus HGTector skipped those organisms. Currently, a workaround will be that you manually download the proteomes, and manually edit the `genome.tsv` file as well as the taxonomy files. This isn't easy though. In the future HGTector may support taxonomy-free analysis, but not now...

**Comment by cfz1998** [comment]
> 
Thank you for your help! I will try other ways.

**Comment by cfz1998** [comment]
> ```python
> plant: 154
> ```

Hi！@qiyunzhu.
How to dispose this error?
![image](https://user-images.githubusercontent.com/60096719/191223177-63647ddc-6bcc-4251-99bb-992e35a3a804.png)
