### ISSUE TITLE
run too long

### ISSUE THREAD

**Issue by zpinocchio** [qiyunlab/HGTector#112]
I use hgtdector run for a protein with 662,394 seqs
commond:
nohup hgtector search -i bins_refs.faa -o HGT -m diamond -p 19 -d nr_20210418_with_taxinfo.dmnd -t NCBI_tax &

it run so long, and no any info output. 
 PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND
20   0  204.1g 201.6g   1432 R 100.0 20.0   9818:31 hgtector

**Comment by qiyunzhu** [comment]
@zpinocchio Thanks for reporting this! Maybe try reducing the number of query sequences? Or specify `--queries 100` such that it will search only 100 query sequences per DIAMOND run.

**Comment by meisiy** [comment]
> @qiyunzhu I know what is wrong! The search.py method taxid_wf
> 
> ```
>         n = len(ids2q)
>         ids2q_ = set(ids2q)
>         if n > 0:
>             print(f'WARNING: Cannot obtain taxIds for {n} sequences. These '
>                   'hits will be dropped.')
>             for hits in prots.values():
>                 for i in reversed(range(len(hits))):
>                     if hits[i]['id'] in ids2q_:
>                         del hits[i]
> ```

Could you please explain why and how to solve it? I met the same problem. Much appreciated.
