### ISSUE TITLE
blast database

### ISSUE THREAD

**Issue by lanlan0210** [qiyunlab/HGTector#113]
Thank you for the excellent software. 
Following the steps in your manual, I have been able to successfully run my own data. However, I have a question about the many files in the hgtdb/blast/ folder, such as db.0nn. In your reply to #46, you mentioned that this is normal because BLAST splits the database into multiple volumes. So, during use, how do I choose which one to use?

**Comment by qiyunzhu** [comment]
Hello @lanlan0210 Thanks for your interest in our program. I am glad to hear that it works! For BLAST, there is no need to specify a single database file. Instead, the "database" parameter is the stem name of all those files, i.e. "db".

**Comment by lanlan0210** [comment]
Thank you very much for your reply. Here's the thing, if I execute the following command 'hgtector search -i /home/XX/temp/hgtector/faa/ -o ./search_dir -m blast -p 32 -d /home/XX/database_download/hgtdb_20230102/blast/db-t /home/XX/database_download/hgtdb_20230102/taxdump/' or 'hgtector search -i /home/XX/temp/hgtector/faa/ -o ./search_dir -m blast -p 32 -d /home/XX/database_download/hgtdb_20230102/db-t /home/XX/database_download/hgtdb_20230102/taxdump/ , it will give an error message which says 'Invalid BLAST database: /home/XX/database_download/hgtdb_20230102/db'. However, if I change 'db' to 'db.nn', the program can run smoothly. So, which one should I choose for the 'dbnn' selection? The files in the /home/xx/database_download/hgtdb_20230102/folder are shown in the following figure. 
![image](https://user-images.githubusercontent.com/49662962/227770486-30451d4e-321f-4636-9c8e-ec23a9bdc2e1.png)

**Comment by EricDeveaud** [comment]
this is dueto the way blast DB is checked in search.py code.
it does.
```
                 if db:
                     if all(isfile(f'{db}.{x}') for x in ('phr', 'pin', 'psq')):
                         return db
                     elif self.method == 'blast':
                         raise ValueError(f'Invalid BLAST database: {db}.')
```

one may want to change it to 
```
                 if db:
                    # check monolithic indexes
                     if all(isfile(f'{db}.{x}') for x in ('phr', 'pin', 'psq')):
                         return db
                    # check splitted indexes. just check *.00.suffix ones
                    elif all(isfile(f'{db}.00.{x}') for x in ('phr', 'pin', 'psq')):
                        return db
                     elif self.method == 'blast':
                         raise ValueError(f'Invalid BLAST database: {db}.')
                 elif self.method == 'blast':
```

regards

Eric

**Comment by qiyunzhu** [comment]
@EricDeveaud Thank you very much for proposing and implementing the solution!! I will merge your pull request #122 . This should solve the problem found by @lanlan0210 .
