### ISSUE TITLE
Extracting downloaded genomic data...Killed

### ISSUE THREAD

**Issue by rsiani** [qiyunlab/HGTector#49]
Hi,
first of all I would like to thank you for developing this tool!

Secondly, I am running the command line 
`hgtector database --output <output_dir> --cats microbe --sample 1 --rank species --reference --representative --compile diamond
`
to build the database. As far as I got it, it has finished to download the genomes but I am not sure the extraction process has been run through, since it always stop with:
Extracting downloaded genomic data...Killed

Could you clarify to me what's going on here? I am not sure whether the operation is finished and if I have all the necessary files.

Bests,
Rob

**Comment by qiyunzhu** [comment]
Hi @rsiani Thank you for your interest in our tool! This "...Killed" note suggests that the error may not be in the Python code, but could be with the job scheduler in your computing system. Did you use any scheduler (e.g., Slurm, Torque)? If so, can you find the job log somehow? Which may record the actual Python error. If this is indeed not an error of Python, then I guess there may be some restriction in write permission in the system.

**Comment by qiyunzhu** [comment]
Let's close this old issue.
