### ISSUE TITLE
Error: Invalid taxonomy mapping file format.

### ISSUE THREAD

**Issue by sarah872** [qiyunlab/HGTector#73]
Hi,
I was constructing the database with this command:
```
hgtector database --output hgtector_refseq-ref-repr_bac-arch_species-all_2020-12-28 --cats bacteria,archaea --rank species --reference --representative --retries 10
```
and then manually compiled it with
```
echo $'accession\taccession.version\ttaxid' > prot.accession2taxid
zcat taxon.map.gz | awk -v OFS='\t' '{split($1, a, "."); print a[1], $1, $2}' >> prot.accession2taxid
module load diamond ncbiblastplus
mkdir diamond blast
gunzip -c taxon.map.gz >taxon.map
makeblastdb -dbtype prot -in db.faa -out blast/db -title db -parse_seqids -taxid_map taxon.map
diamond makedb --threads 8 --in db.faa --taxonmap prot.accession2taxid --taxonnodes taxdump/nodes.dmp --taxonnames taxdump/names.dmp --db diamond/db
```
Unfortunately, diamond threw an error when it came to loading the `prot.accession2taxid`.
```
[...]
Writing accessions...  [3.588s]
Hashing sequences...  [1.296s]
Loading sequences...  [0.001s]
Writing trailer...  [4.612s]
Loading taxonomy...  [0.213s]
Error: Invalid taxonomy mapping file format.
```

I tried it with a new version of taxdump, but the error persists. Is there a way to make the `taxon.map.gz` again without running the entire HGTector database command? I didn't keep the single proteomes because of storage reasons.

Here's a snippet of my `taxon.map.gz`:
```
DABXDW000000000.1	1313
MW052618.1	1313
NP_052604.1	386585
NP_052605.1	386585
NP_052606.1	386585
NP_052607.1	386585
```

and here of the `prot.accession2taxid`:
```
accession	accession.version	taxid
DABXDW000000000	DABXDW000000000.1	1313
MW052618	MW052618.1	1313
NP_052604	NP_052604.1	386585
NP_052605	NP_052605.1	386585
NP_052606	NP_052606.1	386585
NP_052607	NP_052607.1	386585
NP_052608	NP_052608.1	386585
NP_052609	NP_052609.1	386585
```

**Comment by qiyunzhu** [comment]
Hello @sarah872 This is likely because DIAMOND does not like accessions that are longer than 14 characters. I also noticed this issue and discussed with the DIAMOND author. Look at this issue: https://github.com/bbuchfink/diamond/issues/215. According to the author, you need to change `max_accesion_len` in `data/taxonomy.h:47` to some bigger value and re-compile DIAMOND manually.

But it is bit strange to me because `DABXDW000000000.1` is an accession of a nucleotide, not a protein. Not sure how it pops up in the mapping file...

**Comment by sarah872** [comment]
I tried to change and recompile, but the error persists, I tried 50 and 100.
I checked the `prot.accession2taxid`, and none of the fields is empty (all lines have three), and the taxid column only contains numbers.

**Comment by qiyunzhu** [comment]
@sarah872 Given you said, editing the DIAMOND source code does not help. One thing you can try is to modify `taxon.map`. I was surprised to see `DABXDW000000000.1` in your `taxon.map`. Perhaps DIAMOND also got confused with it. While I don't know why it took place, you may filter `taxon.map` to remove any entry that does not exist in `db.faa`. Hope this works. If still not, perhaps you will need to contact the DIAMOND author.

**Comment by sarah872** [comment]
It in fact had something to do with `DABXDW000000000.1`. After removing the line from `prot.accession2taxid`, DIAMOND makedb finished successfully.

```
>DABXDW000000000.1 TPA_asm: Escherichia coli isolate SCCRK18-96, whole genome shotgun sequencing project
NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
```
