### ISSUE TITLE
IndexError:list index out of range

### ISSUE THREAD

**Issue by cccsnd** [qiyunlab/HGTector#78]
Hi everyone, I have run the hgtecor, and got an error message of "IndexError: list index out of range" when analyzing several bacterial genomes.  The error was found in analyze.py of line138 (self.read_input), line266(fname,result……) and line311 (data[-1]['hits'].append(line)). How can I fix this?

**Comment by qiyunzhu** [comment]
Hello @cccsnd Thanks for reporting this issue. After examining the code, I suspect that this problem was caused by an empty search result file. Can you check if that was the case?

**Comment by saimanzano** [comment]
Hello! I am encountering the exact same issue, also on analyze.py lines 138 and 311. In my case, I checked that my search/sample.tsv file is non-empty and that it is in the BLAST outfmt 6 with the fields qaccver saccver pident evalue bitscore qcovhsp staxids, as required

**Comment by qiyunzhu** [comment]
@saimanzano Thanks for reporting this. Could you please share your output file `sample.tsv` with me such that I can try to reproduce this error? My email is qiyunzhu@gmail.com.
