### ISSUE TITLE
about database build!

### ISSUE THREAD

**Issue by sunnycqcn** [qiyunlab/HGTector#87]
Hi Qiyun,
I can build the database manually.  But I can not use the command to build a database. My command is :
` hgtector database -o plant -c plant --default`
The error is following:
`Downloading NCBI taxonomy database... done.
Reading NCBI taxonomy database...Traceback (most recent call last):
  File "/isilon/saskatoon-rdc/users/fuf/comDIR/miniconda/envs/hgtector/bin/hgtector", line 96, in <module>
    main()
  File "/isilon/saskatoon-rdc/users/fuf/comDIR/miniconda/envs/hgtector/bin/hgtector", line 35, in main
    module(args)
  File "/isilon/saskatoon-rdc/users/fuf/comDIR/miniconda/envs/hgtector/lib/python3.8/site-packages/hgtector/database.py", line 124, in __call__
    self.retrieve_taxdump()
  File "/isilon/saskatoon-rdc/users/fuf/comDIR/miniconda/envs/hgtector/lib/python3.8/site-packages/hgtector/database.py", line 268, in retrieve_taxdump
    with tarfile.open(lfile, 'r:gz') as f:
  File "/isilon/saskatoon-rdc/users/fuf/comDIR/miniconda/envs/hgtector/lib/python3.8/tarfile.py", line 1621, in open
    return func(name, filemode, fileobj, **kwargs)
  File "/isilon/saskatoon-rdc/users/fuf/comDIR/miniconda/envs/hgtector/lib/python3.8/tarfile.py", line 1667, in gzopen
    fileobj = GzipFile(name, mode + "b", compresslevel, fileobj)
  File "/isilon/saskatoon-rdc/users/fuf/comDIR/miniconda/envs/hgtector/lib/python3.8/gzip.py", line 173, in __init__
    fileobj = self.myfileobj = builtins.open(filename, mode or 'rb')
FileNotFoundError: [Errno 2] No such file or directory: 'plant/download/taxdump.tar.gz'
`
In fact, I can build a database with the command using your previous version.

Thanks,
Fuyou

**Comment by qiyunzhu** [comment]
Hello Fuyou, I am not able to reproduce this error. Could you try to delete the target directory (`plant/`) and try again? One possible cause is that `-c plant` and `--default` cannot be combined. The latter will instruct the program to target microbes only. I also noticed some recent, undocumented changes in the NCBI FTP server. Not sure if that's the cause...

**Comment by sunnycqcn** [comment]
Hello Qiyun,
You are right. The error is command rsync. If you change to wget, it works well.
`Database building started at 2021-12-03 13:57:20.435417.
The default protocol is selected for database building.
The program will download all protein sequences of NCBI RefSeq genomes of bacteria, archaea, fungi and protozoa, keep one genome per species, plus all NCBI-defined reference and representative genomes.
Downloading NCBI taxonomy database... done.
Reading NCBI taxonomy database... done.
  Total number of TaxIDs: 2384730.
Downloading RefSeq assembly summary... done.
Reading RefSeq assembly summary...Traceback (most recent call last):
  File "/isilon/saskatoon-rdc/users/fuf/comDIR/miniconda/envs/hgtector/bin/hgtector", line 96, in <module>
    main()
  File "/isilon/saskatoon-rdc/users/fuf/comDIR/miniconda/envs/hgtector/bin/hgtector", line 35, in main
    module(args)
  File "/isilon/saskatoon-rdc/users/fuf/comDIR/miniconda/envs/hgtector/lib/python3.10/site-packages/hgtector/database.py", line 127, in __call__
    self.retrieve_summary()
  File "/isilon/saskatoon-rdc/users/fuf/comDIR/miniconda/envs/hgtector/lib/python3.10/site-packages/hgtector/database.py", line 298, in retrieve_summary
    self.df = get_summary('RefSeq')
  File "/isilon/saskatoon-rdc/users/fuf/comDIR/miniconda/envs/hgtector/lib/python3.10/site-packages/hgtector/database.py", line 294, in get_summary
    df = pd.read_table(lfile, skiprows=1, low_memory=False)
  File "/isilon/saskatoon-rdc/users/fuf/comDIR/miniconda/envs/hgtector/lib/python3.10/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/isilon/saskatoon-rdc/users/fuf/comDIR/miniconda/envs/hgtector/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 683, in read_table
    return _read(filepath_or_buffer, kwds)
  File "/isilon/saskatoon-rdc/users/fuf/comDIR/miniconda/envs/hgtector/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 482, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/isilon/saskatoon-rdc/users/fuf/comDIR/miniconda/envs/hgtector/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 811, in __init__
    self._engine = self._make_engine(self.engine)
  File "/isilon/saskatoon-rdc/users/fuf/comDIR/miniconda/envs/hgtector/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 1040, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/isilon/saskatoon-rdc/users/fuf/comDIR/miniconda/envs/hgtector/lib/python3.10/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 51, in __init__
    self._open_handles(src, kwds)
  File "/isilon/saskatoon-rdc/users/fuf/comDIR/miniconda/envs/hgtector/lib/python3.10/site-packages/pandas/io/parsers/base_parser.py", line 222, in _open_handles
    self.handles = get_handle(
  File "/isilon/saskatoon-rdc/users/fuf/comDIR/miniconda/envs/hgtector/lib/python3.10/site-packages/pandas/io/common.py", line 702, in get_handle
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: 'plant/download/assembly_summary_refseq.txt'`
But we need to figure out the NCBI FTP server's changes.
Best,
Fuyou

**Comment by sunnycqcn** [comment]
The reason is that NCBI is updating the database.
I tried to login in NCBI database, there has some changing.
Have a good weekend.
Best,
Fuyou

**Comment by dahezhao** [comment]
Hi Qiyun,
I can not to build my database either. The HGTector version is 2.0b3. My command is:
`hgtector database --output RefSeq_genome --cats microbe --sample 1 --rank species --reference --representative --retries 10 --delay 1 --timeout 5 --compile diamond --threads 32`

The problem I meet is that only 92 protein files could be downloaded at RefSeq_genome/download/faa folder every time. 
The error report is:
> Traceback (most recent call last):
>   File "/export/home/xianghua/xianghua/bio-soft/miniconda2-new/envs/hgtector2/bin/hgtector", line 4, in <module>
>     __import__('pkg_resources').run_script('hgtector==2.0b3', 'hgtector')
>   File "/data1/xianghua/bio-soft/miniconda2-new/envs/hgtector2/lib/python3.9/site-packages/pkg_resources/__init__.py", line 651, in run_script
>     self.require(requires)[0].run_script(script_name, ns)
>   File "/data1/xianghua/bio-soft/miniconda2-new/envs/hgtector2/lib/python3.9/site-packages/pkg_resources/__init__.py", line 1448, in run_script
>     exec(code, namespace, namespace)
>   File "/data1/xianghua/bio-soft/miniconda2-new/envs/hgtector2/lib/python3.9/site-packages/hgtector-2.0b3-py3.9.egg/EGG-INFO/scripts/hgtector", line 96, in <module>
>     main()
>   File "/data1/xianghua/bio-soft/miniconda2-new/envs/hgtector2/lib/python3.9/site-packages/hgtector-2.0b3-py3.9.egg/EGG-INFO/scripts/hgtector", line 35, in main
>     module(args)
>   File "/data1/xianghua/bio-soft/miniconda2-new/envs/hgtector2/lib/python3.9/site-packages/hgtector-2.0b3-py3.9.egg/hgtector/database.py", line 137, in __call__
>     self.download_genomes()
>   File "/data1/xianghua/bio-soft/miniconda2-new/envs/hgtector2/lib/python3.9/site-packages/hgtector-2.0b3-py3.9.egg/hgtector/database.py", line 549, in download_genomes
>     self.ftp.retrbinary(
>   File "/data1/xianghua/bio-soft/miniconda2-new/envs/hgtector2/lib/python3.9/ftplib.py", line 436, in retrbinary
>     with self.transfercmd(cmd, rest) as conn:
>   File "/data1/xianghua/bio-soft/miniconda2-new/envs/hgtector2/lib/python3.9/ftplib.py", line 393, in transfercmd
>     return self.ntransfercmd(cmd, rest)[0]
>   File "/data1/xianghua/bio-soft/miniconda2-new/envs/hgtector2/lib/python3.9/ftplib.py", line 359, in ntransfercmd
>     resp = self.sendcmd(cmd)
>   File "/data1/xianghua/bio-soft/miniconda2-new/envs/hgtector2/lib/python3.9/ftplib.py", line 281, in sendcmd
>     return self.getresp()
>   File "/data1/xianghua/bio-soft/miniconda2-new/envs/hgtector2/lib/python3.9/ftplib.py", line 244, in getresp
>     resp = self.getmultiline()
>   File "/data1/xianghua/bio-soft/miniconda2-new/envs/hgtector2/lib/python3.9/ftplib.py", line 230, in getmultiline
>     line = self.getline()
>   File "/data1/xianghua/bio-soft/miniconda2-new/envs/hgtector2/lib/python3.9/ftplib.py", line 218, in getline
>     raise EOFError
> EOFError

The job can be restarted using the same command, and then another 92 files are downloaded.
Look forward to your suggestion.

With best wishes,
Dahe Zhao

**Comment by qiyunzhu** [comment]
Hello @dahezhao The error you encountered is associated with the program prior to the update. The updated version no longer use ftplib so this is no longer a problem. However the version number didn't change (2.0b3). Could you please uninstall the program and reinstall it and try again? I guess the following should work. But if not, you may have to delete and re-create a conda environment and install the program.

```bash
pip install -U --no-cache-dir git+https://github.com/qiyunlab/HGTector.git
```

**Comment by dahezhao** [comment]
Hello! Qiyun,
We have updated the program according to your suggestion, and now the database could be built successfully. 
Thank you very much!
Dahe

**Comment by qiyunzhu** [comment]
@dahezhao Glad to know that!

**Comment by dahezhao** [comment]
Hello! Qiyun,
I face another question during making the database based on the GTDB taxonomy.

I used the Python 3 script "gtdb_to_taxdump.py" to reformat the file "gtdb_taxonomy.tsv" into NCBI taxdump style. Meanwhile, I downloaded the genomes and obtained the proteins sequences. Based on the output three files (nodes.dmp, names.dmp and taxid.map) and the fasta file including all proteins sequences, I make a prot.accession2taxid file.

After these, I used diamond (v2.0.11.149) to make database according to your suggestion of manual compiling. 
The output is as follow:

> diamond v2.0.11.149 (C) Max Planck Society for the Advancement of Science
> Documentation, support and updates available at http://www.diamondsearch.org
> Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)
> 
> #CPU threads: 16
> Scoring parameters: (Matrix=BLOSUM62 Lambda=0.267 K=0.041 Penalties=11/1)
> Database input file: proteins_2339genomes.faa
> Opening the database file...  [2.676s]
> Loading sequences...  [59.99s]
> Masking sequences...  [11.047s]
> Writing sequences...  [25.778s]
> Writing accessions...  [10.735s]
> Hashing sequences...  [0.933s]
> Loading sequences...  [25.147s]
> Masking sequences...  [3.597s]
> Writing sequences...  [12.176s]
> Writing accessions...  [7.958s]
> Hashing sequences...  [0.28s]
> Loading sequences...  [0s]
> Writing trailer...  [0.145s]
> Loading taxonomy nodes...  [1.669s]
> Error: Invalid taxonomic rank: no rank	|

The error is "Error: Invalid taxonomic rank: no rank	|".
I try to change the format of nodes.dmp file, and sometimes the number of taxonomy nodes processed is zero.
I have excluded the possibility of diamond version, because it could successfully make a database based on the downloaded NCBI taxonomy files.

I donot know how to fix this problem. Look forward to your suggestion.

With best wishes,
Dahe Zhao
