### ISSUE TITLE
Problempre-compiled database from dropbox

### ISSUE THREAD

**Issue by Tonny-zhou** [qiyunlab/HGTector#91]
Dear authors,

Thanks for this great tool! What bothers me now is that due to be in China, I could not download the pre-compiled database from dropbox, as the downloading speed is too slow!

So, could you please think about placing this database in elsewhere, hence i could download it by wget or axel in case of crash during download.

Best reagrds,
Tonny

**Comment by Tonny-zhou** [comment]
Dear authors,

Thanks for this great tool!   What bothers me now is that due to be in China, I could not download the pre-compiled database from dropbox, as the downloading speed is too slow! 

So, could you please think about placing this database in elsewhere, hence i could download it  by wget or axel in case of crash during download.

Beast reagrds,
Tonny

**Comment by qiyunzhu** [comment]
Hello @Tonny-zhou thanks for your interest. Could you please email me at qiyunzhu@gmail.com ? I will share a download link by email.
