### ISSUE TITLE
Database error 

### ISSUE THREAD

**Issue by TaoCheng98** [qiyunlab/HGTector#94]
Hi,

Such a great tool!

I tried to use it with the following command :

``
hgtector database --output  ./hgtector_DB/   --cats microbe --sample 1 --rank species_latin --above --reference --represent --typemater --compile diamond --threads 48
``
But after downloading the data, the script crashed with the following error:
``
Build DIAMOND database...
Traceback (most recent call last):
  File "/home/data/t010208/miniconda3/envs/hgtector/bin/hgtector", line 96, in <module>
    main()
  File "/home/data/t010208/miniconda3/envs/hgtector/bin/hgtector", line 35, in main
    module(args)
  File "/home/data/t010208/miniconda3/envs/hgtector/lib/python3.10/site-packages/hgtector/database.py", line 169, in __call__
    self.compile_database()
  File "/home/data/t010208/miniconda3/envs/hgtector/lib/python3.10/site-packages/hgtector/database.py", line 830, in compile_database
    self.build_diamond_db()
  File "/home/data/t010208/miniconda3/envs/hgtector/lib/python3.10/site-packages/hgtector/database.py", line 884, in build_diamond_db
    raise ValueError(f'diamond failed with error code {ec}.')
ValueError: diamond failed with error code 1.
``

Cound you please tell me how to deal with it?

Thank you,

Chengtao

**Comment by qiyunzhu** [comment]
Hi @TaoCheng98 Thanks for your interest in our tool! This error message suggests that the DIAMOND run failed, but the reason is not immediately clear. I would suggest that you do `--compile | none` in the command, then do [manual compiling](https://github.com/qiyunlab/HGTector/blob/master/doc/database.md#manual-compiling) on the downloaded protein sequences. That will let you see the actual reason, and hopefully let you complete database building.

**Comment by qiyunzhu** [comment]
@TaoCheng98 No worry! Glad to learn that you have solved the problem!

**Comment by TaoCheng98** [comment]
Hi,

Qiyun,

When I used the following command to identify HGT in Mtb, my results showed up over 500 HGT.

`hgtector search  -i /home/data/t010208/Chengtao/hgtector/input/uniprot  -o /home/data/t010208/Chengtao/hgtector/output_uniprot   -t  /home/data/t010208/Chengtao/hgtector/hgtdb_2/taxdump -d /home/data/t010208/Chengtao/hgtector/hgtdb_2/diamond/db -m diamond  --maxhits 500 --minsize 50 --evalue 1e-5 --identity 50 --coverage 50 --maxseqs 1000   -p 96
hgtector analyze -i /home/data/t010208/Chengtao/hgtector/output_id95/search/Mtb.tsv -o /home/data/t010208/Chengtao/hgtector/output_id95  -t /home/data/t010208/Chengtao/hgtector/hgtdb_2/taxdump  --donor-name `

Surprisingly, a large number of ribosomal proteins are thought to be HGT.This is unlikely to be true.I don't know how to explain this.




I do not think that M. tuberculosis is so special that HGTecter should not be used.But I really don't understand the problem.

Best,


Chengtao

**Comment by qiyunzhu** [comment]
Hello @TaoCheng98 I agree that your result sounds counter intuitive. Chance for ribosomal proteins to be transferred is extremely low. I would suggest that you read this [tutorial](https://github.com/qiyunlab/HGTector/blob/master/doc/2ndrun.md) regarding diagnosing by plots (kernel density plots) and setting the three groups. HGTector can automatically infer the three groups based on taxonomy, however that may not be the optimal ones or the ones that are suitable for your research. You may consider specifying them manually based on your a prior knowledge. Hope it helps!
