### ISSUE TITLE
DIAMOND failed with error code 139

### ISSUE THREAD

**Issue by malleryc** [qiyunlab/HGTector#95]
Hi,

I am using HGTector2 and keep coming across trouble when attempting to use the search function with the following command: hgtector search -i ../../../METABOLIC_running_folder/21_.faa/ -o analyze_dir -s ../../../METABOLIC_running_folder/21_.faa -m diamond -d db.faa -p 16 --tax-include 2 

which immediately results in: 

Homology search started at 2022-07-19 18:08:50.919896.
WARNING: Local taxonomy database is not specified. Will try to retrieve taxonomic information from remote server.
Settings:
  Search method: diamond.
  Self-alignment method: native.
  Remote fetch enabled: yes.
Reading input proteins...
  GCF_000948415.1_ASM94841v1_genomic.fna.simple: 3879 proteins.
  GCF_002115755.1_ASM211575v1_genomic.fna.simple: 4321 proteins.
  GCF_003403095.1_ASM340309v1_genomic.fna.simple: 4319 proteins.
  GCF_002844275.1_ASM284427v1_genomic.fna.simple: 4331 proteins.
  GCF_011806525.1_ASM1180652v1_genomic.fna.simple: 3871 proteins.
  GCF_011927685.1_ASM1192768v1_genomic.fna.simple: 4032 proteins.
  GCF_001907695.1_ASM190769v1_genomic.fna.simple: 4401 proteins.
  GCF_002115825.1_ASM211582v1_genomic.fna.simple: 5212 proteins.
  GCF_011806425.1_ASM1180642v1_genomic.fna.simple: 4000 proteins.
  GCF_002844235.1_ASM284423v1_genomic.fna.simple: 4009 proteins.
  GCF_002115785.1_ASM211578v1_genomic.fna.simple: 4162 proteins.
  GCF_002115745.1_ASM211574v1_genomic.fna.simple: 4308 proteins.
  GCF_000763295.1_ASM76329v1_genomic.fna.simple: 3877 proteins.
  GCF_003326675.1_ASM332667v1_genomic.fna.simple: 4421 proteins.
  GCF_003326795.1_ASM332679v1_genomic.fna.simple: 4329 proteins.
  our_thalassospira: 4688 proteins.
  GCF_002844375.1_ASM284437v1_genomic.fna.simple: 4690 proteins.
  GCF_003326775.1_ASM332677v1_genomic.fna.simple: 4378 proteins.
  GCF_001613795.1_ASM161379v1_genomic.fna.simple: 3958 proteins.
  GCF_003326475.1_ASM332647v1_genomic.fna.simple: 4896 proteins.
Done. Read 86082 proteins from 20 samples.
Dropping sequences shorter than 30 aa... done.
Reading custom taxonomy database... done.
  Read 1 taxa.
Batch homology search of GCF_000763295.1_ASM76329v1_genomic.fna.simple started at 2022-07-19 18:08:52.258553.
Number of queries: 3876.

and after a few minutes the following string of errors:
Traceback (most recent call last):
  File "/home/malleryc/.conda/envs/hgtector/bin/hgtector", line 96, in <module>
    main()
  File "/home/malleryc/.conda/envs/hgtector/bin/hgtector", line 35, in main
    module(args)
  File "/home/malleryc/.conda/envs/hgtector/lib/python3.9/site-packages/hgtector/search.py", line 164, in __call__
    res = self.search_wf(
  File "/home/malleryc/.conda/envs/hgtector/lib/python3.9/site-packages/hgtector/search.py", line 691, in search_wf
    res = self.diamond_search(seqs)
  File "/home/malleryc/.conda/envs/hgtector/lib/python3.9/site-packages/hgtector/search.py", line 1537, in diamond_search
    raise ValueError(f'diamond failed with error code {ec}.')
ValueError: diamond failed with error code 139.

I would like to add that this is using the 2019-10-21 database (although I have tried with both) and using diamond v.2.0.13. Any help or suggestions you may have would be greatly appreciated.

**Comment by qiyunzhu** [comment]
Hello @malleryc Thanks for your interest in our program. Exit code 139 might be a segmentation fault when executing DIAMOND. This is hard to debug...

First, how much memory are available in the system? If it's a laptop you might run out of memory.

Second, you may try to do the search separately and feed the results to HGTector. Here is [how](https://github.com/qiyunlab/HGTector/blob/master/doc/search.md#pre-computed-search-result).

Third, you may try DIAMOND v0.9.x (maybe v0.9.25) for the 2019 database to see it that works.

Hope these help! Let me know whatever you encounter. Thanks!

**Comment by malleryc** [comment]
Thank you for your response and helpful suggestions! To answer your question and follow up on your advice:

There is 64Gb of memory on the system. I attempted to run the search seperately with the following command:

hgtector search -i ../../../METABOLIC_running_folder/21_.faa/ -o analyze_dir -m diamond -d db.faa -p 16 --tax-include 2

which resulted in the same error.

Additionally, I did try using an older version of diamond where I was met with "diamond failed with exit code 1." which I have previously been able to work around using a newer version of diamond.

**Comment by qiyunzhu** [comment]
Hello @malleryc Thanks for the update. Given this, I would suggest that you try the 2nd solution (manually run DIAMOND) and see if the error persists. If there is no error, then HGTector's code may need to be updated in order to work with the latest DIAMOND versions.

**Comment by malleryc** [comment]
Thank you again for the helpful suggestion. I mannually ran DIAMOND and in trying to feed the results to HGTector (with the following command):

hgtector search -i ../../../METABOLIC_running_folder/21_.faa/  --precomp blastp/ -o analyze_dir/ -p 16 --tax-include 2

 I am met with a new error: 
Traceback (most recent call last):
  File "/home/malleryc/.conda/envs/hgtector/bin/hgtector", line 96, in <module>
    main()
  File "/home/malleryc/.conda/envs/hgtector/bin/hgtector", line 35, in main
    module(args)
  File "/home/malleryc/.conda/envs/hgtector/lib/python3.9/site-packages/hgtector/search.py", line 165, in __call__
    batch, self.pcmap[sid] if self.method == 'precomp'
KeyError: 'GCF_000763295.1_ASM76329v1_genomic.fna.simple'

I was not sure if this error was a result of a naming issue with my genomes or what it might be. Again, thank you for your helpful suggestions!

**Comment by qiyunzhu** [comment]
Hi @malleryc thanks for the update. It seems that the manual DIAMOND run worked. The subsequent HGTector error may be because your DIAMOND output directory `blastp/` does not contain one file per input genome. For example, if your input file is called `GCF_000763295.1_ASM76329v1_genomic.fna.simple.faa`, then there should be a `GCF_000763295.1_ASM76329v1_genomic.fna.simple.txt` (`txt` is arbitrary) in your `blastp/`. Is that the case?

**Comment by malleryc** [comment]
It turned out there were a few dissimilarities. Thank you for that helpful suggestion, the search ran smoothly until I unexpectedly had to interrupt the process early. 

Now in running it with the same code it has an error:

ValueError: Invalid query sequence Id: c_000000000001_1.
which is reffering to the  DIAMOND output directory input file

I am not sure if there is a way to pick up on a previously started process to get around this issues with the DIAMOND output directory files.

**Comment by qiyunzhu** [comment]
Hi @malleryc I looked at your command in the initial post more carefully and found an issue:

```bash
hgtector search -i ../../../METABOLIC_running_folder/21_.faa/ -o analyze_dir -s ../../../METABOLIC_running_folder/21_.faa -m diamond -d db.faa -p 16 --tax-include 2
```

The parameter `-d db.faa` is probably not right. This should be a compiled DIAMOND database with taxonomic information included. HGTector's [database](https://github.com/qiyunlab/HGTector/blob/master/doc/database.md) command will help you to make the database. Assuming that the database directory is 'where', then the correct parameter should `-d where/diamond/db`.

Hope this helps.

**Comment by malleryc** [comment]
Thank you for your response, it does look like I did not do the compiling steps after downloading the database. I have since completed these steps and tried running a search with the following command:
hgtector search -i ../../METABOLIC_running_folder/21_.faa/ -m precomp -s db_dir/blastp/ -o . -t hgtdb_20211121/taxdump/ --taxmap hgtdb_20211121/taxon.map.gz -p 32

Which returned the following errors which I am unsure on how to resolve:
Importing pre-computed search results...Traceback (most recent call last):
  File "/home/malleryc/.conda/envs/hgtector/bin/hgtector", line 96, in <module>
    main()
  File "/home/malleryc/.conda/envs/hgtector/bin/hgtector", line 35, in main
    module(args)
  File "/home/malleryc/.conda/envs/hgtector/lib/python3.9/site-packages/hgtector/search.py", line 164, in __call__
    res = self.search_wf(
  File "/home/malleryc/.conda/envs/hgtector/lib/python3.9/site-packages/hgtector/search.py", line 680, in search_wf
    res = self.parse_hit_table(file, lenmap)
  File "/home/malleryc/.conda/envs/hgtector/lib/python3.9/site-packages/hgtector/search.py", line 1703, in parse_hit_table
    return (self.parse_m8_table(lines, lenmap) if ism8 else
  File "/home/malleryc/.conda/envs/hgtector/lib/python3.9/site-packages/hgtector/search.py", line 1785, in parse_m8_table
    raise ValueError(f'Invalid query sequence Id: {x[0]}.')
ValueError: Invalid query sequence Id: c_000000000040_3.

**Comment by malleryc** [comment]
I wanted to follow up to say that I resolved this issue and was able to complete the pipeline with no issues. I apprecieate your help and suggestions while troubleshooting!
