### ISSUE TITLE
Build Reference Database Issue: EOFError

### ISSUE THREAD

**Issue by KarimAI7** [qiyunlab/HGTector#99]
I tried building a reference databse using the default protocol `hgtector database -o db_dir --default`, but here is the output I am getting.

`(hgtector) user@dell:~/Documents/Faucher/Sequencing_Softwares/hgtector$ hgtector database -o db_dir --default
Database building started at 2022-08-13 06:32:19.268525.
The default protocol is selected for database building.
The program will download all protein sequences of NCBI RefSeq genomes of bacteria, archaea, fungi and protozoa, keep one genome per species, plus all NCBI-defined reference and representative genomes.
Connecting to the NCBI FTP server... done.
Downloading NCBI taxonomy database... done.
Reading NCBI taxonomy database... done.
Total number of TaxIDs: 2438258.
Downloading RefSeq assembly summary... done.
Reading RefSeq assembly summary... done.
Total number of genomes: 270091.
Genome categories:  archaea, bacteria, fungi, protozoa
Downloading genome list per RefSeq category...
  archaea: 1309
  bacteria: 287062
  fungi: 458
  protozoa: 95
Done.
Total number of genomes in categories: 257467.
Filtering genomes...
Done.
Identifying taxonomy of genomes...
  Dropped 44 genomes without captalized organism name.
Done.
Sampling genomes based on taxonomy...
Up to 1 genome(s) will be sampled per species.
Total number of taxonomic groups at species: 38425.
Add reference genomes back to selection.
Add representative genomes back to selection.
Total number of sampled genomes: 38430.
Downloading non-redundant genomic data from NCBI...
  G000001985
  G000002415
  G000002435
  G000002445
  G000002455
  G000002495
  G000002515
  G000002525
  G000002545
  G000002655
  G000002715
  G000002725
  G000002825
  G000002845
  G000002855
  G000002875
  G000002945
  G000003125
  G000003225
  G000003515
  G000003525
  G000003835
  G000003855
  G000004155
  G000004695
  G000004825
  G000004985
  G000005825
  G000005845
  G000006335
  G000006355
  G000006405
  G000006425
  G000006445
  G000006515
  G000006565
  G000006605
  G000006685
  G000006765
  G000006825
  G000006925
  G000006945
  G000006985
  G000007025
  G000007065
  G000007085
  G000007105
  G000007125
  G000007185
  G000007205
  G000007225
  G000007245
  G000007345
  G000007505
  G000007605
  G000007625
  G000007725
  G000007745
  G000007765
  G000007805
  G000007905
  G000007925
  G000007985
  G000008185
  G000008265
  G000008305
  G000008325
  G000008365
  G000008385
  G000008445
  G000008465
  G000008625
  G000008645
  G000008725
  G000008865
  G000009045
  G000009085
  G000009145
  G000009185
  G000009305
  G000009365
  G000009705
  G000009725
  G000009765
  G000009785
  G000009805
  G000009905
  G000009945
  G000009965
  G000009985
  G000010085
  G000010205
Traceback (most recent call last):
  File "/home/user/anaconda3/envs/hgtector/bin/hgtector", line 96, in <module>
    main()
  File "/home/user/anaconda3/envs/hgtector/bin/hgtector", line 35, in main
    module(args)
  File "/home/user/anaconda3/envs/hgtector/lib/python3.8/site-packages/hgtector/database.py", line 137, in __call__
    self.download_genomes()
  File "/home/user/anaconda3/envs/hgtector/lib/python3.8/site-packages/hgtector/database.py", line 540, in download_genomes
    self.ftp.retrbinary(
  File "/home/user/anaconda3/envs/hgtector/lib/python3.8/ftplib.py", line 432, in retrbinary
    with self.transfercmd(cmd, rest) as conn:
  File "/home/user/anaconda3/envs/hgtector/lib/python3.8/ftplib.py", line 389, in transfercmd
    return self.ntransfercmd(cmd, rest)[0]
  File "/home/user/anaconda3/envs/hgtector/lib/python3.8/ftplib.py", line 355, in ntransfercmd
    resp = self.sendcmd(cmd)
  File "/home/user/anaconda3/envs/hgtector/lib/python3.8/ftplib.py", line 277, in sendcmd
    return self.getresp()
  File "/home/user/anaconda3/envs/hgtector/lib/python3.8/ftplib.py", line 240, in getresp
    resp = self.getmultiline()
  File "/home/user/anaconda3/envs/hgtector/lib/python3.8/ftplib.py", line 226, in getmultiline
    line = self.getline()
  File "/home/user/anaconda3/envs/hgtector/lib/python3.8/ftplib.py", line 214, in getline
    raise EOFError
EOFError
`

**Comment by qiyunzhu** [comment]
Hi @KarimAI7 You might be using an older version of HGTector, which had issues with the latest NCBI server. You can update HGTector by:

```bash
pip install --force-reinstall --no-cache-dir git+https://github.com/qiyunlab/HGTector.git
```
